### ISSUE TITLE
gnuradio error

### ISSUE THREAD

**Issue by G55366** [analogdevicesinc/adi-kuiper-gen#123]
On the board startup printing interface, there will be “failed to start VNC server for X11”
run "gnuradio-companion"have error:
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "/usr/bin/gnuradio-companion", line 102, in <module>
    run_main()
  File "/usr/bin/gnuradio-companion", line 95, in run_main
    exit(main())
  File "/usr/lib/python3/dist-packages/gnuradio/grc/main.py", line 81, in main
    from .gui.Platform import Platform
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/Platform.py", line 26, in <module>
    from . import canvas
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/canvas/__init__.py", line 21, in <module>
    from .param import Param
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/canvas/param.py", line 23, in <module>
    from .. import ParamWidgets, Utils, Constants
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 69, in <module>
    add_style_provider()
  File "/usr/lib/python3/dist-packages/gnuradio/grc/gui/ParamWidgets.py", line 64, in add_style_provider
    Gtk.StyleContext.add_provider_for_screen(
TypeError: Argument 0 does not allow None as a value

**Comment by SRaus** [comment]
Problem is fixed in last Kuiper images: [Kuiper Linux Release Notes](https://wiki.analog.com/resources/tools-software/linux-software/adi-kuiper_images/release_notes )
